version: "3"
services:
  nginx:
    image: nginx:1-alpine
    volumes:
     - ../nginx/nginx.conf:/etc/nginx/conf.d/nginx.conf
     - ../nginx/common:/usr/share/nginx/html/common
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
    ports:
      - "3000:3000"
    networks:
      - webnet
    environment:
      - TEAMCITY_PROJECT_NAME	  
networks:
  webnet: